package Idioter::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Idioter::Schema',
    
    
);

=head1 NAME

Idioter::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Idioter>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Idioter::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.29

=head1 AUTHOR

Andreas Marienborg

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
